-- Description: Oracle 테이블 생성 스크립트

-- 시퀀스 생성
CREATE SEQUENCE SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 999999
  NOCYCLE
  NOORDER;

-- TBL_VEHICLE 테이블 생성
CREATE TABLE TBL_VEHICLE (
  SEQ            NUMBER          NOT NULL,
  CAR_NO         VARCHAR2(8)     NOT NULL,
  BASE_DATE      VARCHAR2(8)     DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
  PROG_FLAG      VARCHAR2(2)     DEFAULT '01' NOT NULL,
  EXEMPT_STATUS  VARCHAR2(2)     DEFAULT '99' NOT NULL,
  IC_CODE        VARCHAR2(3)     NOT NULL,
  WORK_DATE      VARCHAR2(8)     NOT NULL,
  WORK_NO        VARCHAR2(4)     NOT NULL,
  HAND_SNO       NUMBER          NOT NULL,
  VEHICLE_TYPE   VARCHAR2(2)     DEFAULT '01' NOT NULL,
  PASS_TIME      DATE,
  VEHICLE_KIND   VARCHAR2(2)     NOT NULL,
  REG_ID         VARCHAR2(10)    DEFAULT 'RPA' NOT NULL,
  REG_DT         DATE            DEFAULT SYSDATE NOT NULL,
  MOD_ID         VARCHAR2(10)    DEFAULT 'RPA' NOT NULL,
  MOD_DT         DATE            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_TBL_VEHICLE PRIMARY KEY (SEQ, CAR_NO, BASE_DATE) -- 기본 키 제약 조건
);

-- 테이블 및 컬럼 코멘트 추가
COMMENT ON TABLE TBL_VEHICLE IS '면제 차량 요청'; -- TBL_VEHICLE 테이블 설명
COMMENT ON COLUMN TBL_VEHICLE.SEQ IS '순번';
COMMENT ON COLUMN TBL_VEHICLE.CAR_NO IS '차량번호';
COMMENT ON COLUMN TBL_VEHICLE.BASE_DATE IS '기준일자 (형식: YYYYMMDD)';
COMMENT ON COLUMN TBL_VEHICLE.PROG_FLAG IS '진행 FLAG (01 : API 요청 ,02 : API 처리중  ,03 : API 완료  ,04 : RPA 사용완료)';
COMMENT ON COLUMN TBL_VEHICLE.EXEMPT_STATUS IS '면제여부 (01 : 면제아님 ,02 : 조회불능 ,03 : 다자녀 04 : 유공자 ,05 : 장애인  ,06 : 전기(부산)  ,07 : 수소(부산)  ,08 : 공차(택시)  ,99 : 면제여부 조회전)';
COMMENT ON COLUMN TBL_VEHICLE.IC_CODE IS '영업소ID';
COMMENT ON COLUMN TBL_VEHICLE.WORK_DATE IS '업무일자';
COMMENT ON COLUMN TBL_VEHICLE.WORK_NO IS '업무번호';
COMMENT ON COLUMN TBL_VEHICLE.HAND_SNO IS '차량일련번호';
COMMENT ON COLUMN TBL_VEHICLE.VEHICLE_TYPE IS '차량타입 (01 : 일반, 02 : 택시 (부산/경남) 10건씩 읽어드려서 36시간 뒤에 순차적으로 요청)';
COMMENT ON COLUMN TBL_VEHICLE.PASS_TIME IS '통과시간 (01 : 일반차량일 경우 입력안해도 됨  ,02 : 택시일 경우는 반드시 입력 되어야 함 )';
COMMENT ON COLUMN TBL_VEHICLE.VEHICLE_KIND IS '차량종류 (국토부(차량 분류코드 VHCTY_SE_CODE 동일) 01 : 소형  ,02 : 중형  ,03 : 대형  ,04 : 경형  ,05 : 저상형  ,06 : 고상형  ,07 : 작제함형,   ,08 : 샷시형  ,09 : 기타형) ';
COMMENT ON COLUMN TBL_VEHICLE.REG_ID IS '작성자';
COMMENT ON COLUMN TBL_VEHICLE.REG_DT IS '작성일';
COMMENT ON COLUMN TBL_VEHICLE.MOD_ID IS '수정자';
COMMENT ON COLUMN TBL_VEHICLE.MOD_DT IS '수정일';

-- 테이블 및 컬럼 코멘트 추가
CREATE TABLE TBL_VEHICLE_MST (
  CAR_NO         VARCHAR2(8)     NOT NULL,
  BASE_DATE      VARCHAR2(8)     DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
  EXEMPT_STATUS  VARCHAR2(2)     NOT NULL,
  VEHICLE_KIND   VARCHAR2(2)     NOT NULL,
  REG_ID         VARCHAR2(10)    DEFAULT 'BATCH' NOT NULL,
  REG_DT         DATE            DEFAULT SYSDATE NOT NULL,
  MODI_ID        VARCHAR2(10)    DEFAULT 'BATCH' NOT NULL,
  MODI_DT        DATE            DEFAULT SYSDATE NOT NULL,
  PRIMARY KEY (CAR_NO)
);

-- 테이블 및 컬럼 코멘트 추가
COMMENT ON TABLE TBL_VEHICLE_MST IS '면제 차량 MASTER'; -- TBL_VEHICLE_MST 테이블 설명
COMMENT ON COLUMN TBL_VEHICLE_MST.CAR_NO IS '차량번호';
COMMENT ON COLUMN TBL_VEHICLE_MST.BASE_DATE IS '기준일자 (형식: YYYYMMDD)';
COMMENT ON COLUMN TBL_VEHICLE_MST.EXEMPT_STATUS IS '면제여부 (01 : 면제아님 ,02 : 조회불능 ,03 : 다자녀 04 : 유공자 ,05 : 장애인  ,06 : 전기(부산)  ,07 : 수소(부산)  ,08 : 공차(택시)  ,99 : 면제여부 조회전)';
COMMENT ON COLUMN TBL_VEHICLE_MST.VEHICLE_KIND IS '차량종류 (국토부(차량 분류코드 VHCTY_SE_CODE 동일) 01 : 소형  ,02 : 중형  ,03 : 대형  ,04 : 경형  ,05 : 저상형  ,06 : 고상형  ,07 : 작제함형,   ,08 : 샷시형  ,09 : 기타형) ';
COMMENT ON COLUMN TBL_VEHICLE_MST.REG_ID IS '작성자';
COMMENT ON COLUMN TBL_VEHICLE_MST.REG_DT IS '작성일';
COMMENT ON COLUMN TBL_VEHICLE_MST.MODI_ID IS '수정자';
COMMENT ON COLUMN TBL_VEHICLE_MST.MODI_DT IS '수정일';

-- TBL_CODE 테이블 생성
CREATE TABLE TBL_CODE (
    CODE VARCHAR2(2) NOT NULL, -- 코드
    CODE_NAME VARCHAR2(30) NOT NULL, -- 코드명
    REG_ID VARCHAR2(10) DEFAULT 'RPA', -- 작성자 ID
    REG_DT DATE DEFAULT SYSDATE, -- 작성일
    MODI_ID VARCHAR2(10) DEFAULT 'RPA', -- 수정자 ID
    MODI_DT DATE DEFAULT SYSDATE, -- 수정일
    CONSTRAINT PK_TBL_CODE PRIMARY KEY (CODE) -- 기본 키 제약 조건
);

-- 테이블 및 컬럼 코멘트 추가
COMMENT ON TABLE TBL_CODE IS '면제 차량 MASTER'; -- TBL_CODE 테이블 설명
COMMENT ON COLUMN TBL_CODE.CODE IS '코드'; -- 코드
COMMENT ON COLUMN TBL_CODE.CODE_NAME IS '코드명'; -- 코드명
COMMENT ON COLUMN TBL_CODE.REG_ID IS '작성자'; -- 작성자 ID
COMMENT ON COLUMN TBL_CODE.REG_DT IS '작성일'; -- 작성일
COMMENT ON COLUMN TBL_CODE.MODI_ID IS '수정자'; -- 수정자 ID
COMMENT ON COLUMN TBL_CODE.MODI_DT IS '수정일'; -- 수정일